In [183]:
import pandas as pd
import numpy as np


In [184]:
from sklearn.datasets import make_classification
X,y=make_classification( n_samples=1000,n_features=10,n_informative=2)

In [185]:
X

array([[ 0.07994036, -0.24456764, -0.44653096, ..., -1.49540723,
        -1.01514246, -0.24577172],
       [-1.77005526, -1.138244  ,  0.81411096, ...,  1.4776459 ,
         0.59496113,  0.35767769],
       [-0.78606582,  0.35248041, -0.50531598, ..., -0.12315002,
        -0.24634726, -0.32197286],
       ...,
       [ 0.35825547,  1.24379437,  1.10110185, ..., -1.52284466,
        -0.66747484, -0.56011116],
       [ 0.90987237,  1.26801108,  0.42522822, ...,  1.72344956,
        -0.15080843, -0.71325949],
       [ 1.45342445,  0.24477761, -1.04906022, ...,  0.34701334,
        -0.49076295, -0.90793954]])

In [186]:
y

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,

In [187]:
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [188]:
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.2,random_state=42)

# decision tree

In [189]:
dt=DecisionTreeClassifier(random_state=42)
dt.fit(X_train,Y_train)

DecisionTreeClassifier(random_state=42)

In [190]:
Y_pred=dt.predict(X_test)
Y_pred

array([1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1])

In [191]:
accuracy_score(Y_pred,Y_test)

0.965

# Bagging

In [192]:
from sklearn.ensemble import BaggingClassifier

In [193]:
bag=BaggingClassifier(n_estimators=200,max_samples=0.50,bootstrap=True,random_state=42)
bag.fit(X_train,Y_train)
Y_pred=bag.predict(X_test)
accuracy_score(Y_pred,Y_test)

0.99

In [194]:
bag.estimators_samples_[0].shape

(400,)

In [195]:
bag.estimators_samples_

[array([475,  41, 332, 642, 231, 604, 711, 370, 632, 540, 745, 596,   6,
        324, 338, 307, 105, 586, 290, 260,   8, 398, 288, 510, 571, 607,
        505, 515, 150, 363, 116, 455, 194, 361, 437, 589, 184, 336, 754,
        753, 725,  64, 768, 378,  59, 615, 491, 337, 553, 437, 582, 132,
        256, 572, 791, 412, 526, 746, 249, 183, 203, 465, 340, 677, 100,
        685, 725,  23, 582,   1, 337, 172, 294, 353,  52, 521, 338, 327,
        109,  73, 447, 217, 196, 499,  14, 288, 616, 616, 557, 492, 565,
        773, 146,  36, 303, 791, 752,  39, 632, 292, 512, 470, 135, 254,
        634, 437, 781, 734, 265,  15, 703, 774, 333,  48,  27, 582, 476,
        316, 476, 404, 685,  49, 131, 268, 481,  85, 184, 303,  99, 375,
        401, 513, 602, 756, 739, 166, 763, 548, 598, 748, 576,  66, 723,
         68, 332, 599, 733, 605, 110,  79, 464, 577, 500, 208, 313, 711,
        587,   5, 710, 200, 358, 270,   1, 669,  26, 609, 272, 385, 751,
        224, 472, 322, 687, 763, 650, 245,  62, 121

In [196]:
bag.estimators_features_[0].shape

(10,)

In [197]:
bag.estimators_features_

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),


In [198]:
from sklearn.svm import SVC
svm=SVC()

# svm

In [199]:
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier

bag = BaggingClassifier(base_estimator=SVC(), n_estimators=200, max_samples=0.50, bootstrap=True, random_state=42)
bag.fit(X_train, Y_train)


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


BaggingClassifier(base_estimator=SVC(), max_samples=0.5, n_estimators=200,
                  random_state=42)

In [200]:
Y_pred=bag.predict(X_test)
accuracy_score(Y_pred,Y_test)

0.98

# patching

In [201]:
## no change in row and column ,max_samples=1.0

In [202]:
bag=BaggingClassifier(estimator=DecisionTreeClassifier(),n_estimators=200,max_samples=1,bootstrap=False ,random_state=42)
bag.fit(X_train,Y_train)
Y_pred=bag.predict(X_test)
accuracy_score(Y_pred,Y_test)

0.53

# Random Patching

In [203]:
#max_samples-row
#    bootstrap_features=True-column,

In [204]:
bag=BaggingClassifier(estimator=DecisionTreeClassifier(),n_estimators=200,max_samples=0.25,bootstrap=True,bootstrap_features=True,random_state=42)
bag.fit(X_train,Y_train)
Y_pred=bag.predict(X_test)
accuracy_score(Y_pred,Y_test)

0.975

In [205]:
#out-of-bag samples  is a measure of the model's performance on unseen data

#  out-of-bag(oob) 

In [206]:
bag=BaggingClassifier(estimator=DecisionTreeClassifier(),n_estimators=200,max_samples=0.25,bootstrap=True,oob_score=True,random_state=42)
bag.fit(X_train,Y_train)
Y_pred=bag.predict(X_test)
accuracy_score(Y_pred,Y_test)

0.97

In [207]:
bag.oob_score

True

In [208]:
bag.oob_score_

0.955